# Generated by Django 4.0.6 on 2022-10-20 14:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tv_shows', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='users/images/default.png', upload_to='users/images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTvShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watched', 'watched'), ('watching', 'watching'), ('planning', 'planning'), ('on-hold', 'on-hold'), ('dropped', 'dropped')], default='watched', max_length=20)),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('tv_show', models.ForeignKey(db_column='tmdb_id', on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'unique_together': {('user', 'tv_show')},
            },
        ),
        migrations.CreateModel(
            name='UserSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('episodes_watched', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('date_started', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1928, 9, 11))])),
                ('date_finished', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1928, 9, 11))])),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'season')},
            },
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watched', 'watched'), ('watching', 'watching'), ('planning', 'planning'), ('on-hold', 'on-hold'), ('dropped', 'dropped')], default='watched', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('date_watched', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1895, 12, 28))])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(db_column='tmdb_id', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
