# Generated by Django 4.0.6 on 2022-10-20 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('overview', models.TextField(blank=True, max_length=1024, null=True)),
                ('first_air_date', models.DateField(null=True)),
                ('last_air_date', models.DateField(null=True)),
                ('poster_path', models.CharField(blank=True, max_length=256, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('rumored', 'rumored'), ('planned', 'planned'), ('in production', 'in production'), ('post production', 'post production'), ('released', 'released'), ('canceled', 'canceled')], default='released', max_length=20)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('popularity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='TvShowPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=256, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.role')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='TvShowGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('overview', models.TextField(blank=True, max_length=1024, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=256, null=True)),
                ('number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('overview', models.TextField(blank=True, max_length=1024, null=True)),
                ('air_date', models.DateField(null=True)),
                ('runtime', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('poster_path', models.CharField(blank=True, max_length=256, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.season')),
            ],
        ),
    ]
